### PR TITLE
add flags in peers section

### PR DESCRIPTION
**Pull request by rsalas**
Flags are added in peers
The configuration for the flags is added in dialogs
Country_Flags
Config IpInfo

### CODE REVIEW

**Comment by ronggang** [comment]
Thanks, Too many content updates, I try to merge.

**Comment by vodek3** [comment]
Am I understand correctly that to display flags at peers, you need to put the code from the Profile from IPinfo.io in the IPinfo.io Token field in the Config -> More -> field?
IPinfo io Маркер доступа (Access Token)

**Comment by rsalas** [comment]
Yes, this is the token.

**Comment by vodek3** [comment]
Но когда я ввожу токен в настройки пиры не отображаются вовсе...
IPinfo io Маркер доступа (Access Token) 2

**Comment by rsalas** [comment]
The variable "flags" should be lost in the conflict...

I have put another pull request

**Comment by vodek3** [comment]
I thought now.
It would be convenient in the Config dialog in the More tab to place a link to https://ipinfo.io/account/

**Comment by ronggang** [comment]
@rsalas Can’t work in the new version(86.x.x.x) of Chrome (Mac, Windows) because it’s cross-domain.

**Comment by rsalas** [comment]
It should work, because calls are GET and GET calls are allowed in the
cross-domain, the calls not allowed are POST calls.

**Comment by ronggang** [comment]
> It should work, because calls are GET and GET calls are allowed in the cross-domain, the calls not allowed are POST calls. 

It's my mistake, I turned on the uBlock.

**Comment by rsalas** [comment]
No problem, with JSONP is better.

**Pull request merged**
