### PR TITLE
add global variable flags

### PR DESCRIPTION
**Pull request by rsalas**

### CODE REVIEW

**Comment by vodek3** [comment]
It's work!
изображение

**Comment by vodek3** [comment]
By the way. It will be prettier if the flag is placed left from IP address. Is it possible?

**Comment by rsalas** [comment]
Yes, is a easy change. Tomorrow send a pull request.

**Comment by imebeh** [comment]
end of line 374 @ es.json, missed a comma(,)

**Comment by rsalas** [comment]
Yes, you have a PR with all change.

**Pull request merged**
