### PR TITLE
Fixes for v1.6.0 alpha (20180418)

### PR DESCRIPTION
**Pull request by Monter**
Update languages (PL, EN and default) - typos and unification)
Move spaces in statistic tree from lang files to system
Repair tree data color in black theme

### CODE REVIEW

**Comment by auanasgheps** [comment]
What is the difference between _default_ and _en_ language files? I am re-translating Italian language using **en language** file as a source.

**Comment by Monter** [comment]
There should be no difference, unfortunately in version 1.6.0 alpha new options have been added only to the default file.

**Comment by auanasgheps** [comment]
I can see you're updating many languages - don't bother fixing Italian, I am using the new file and will push the update when completed.

**Comment by ronggang** [comment]
Maybe in the next release, `default.js` and `en.js` will be merged.

**Pull request merged**
