### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by vodek3**
I don’t have no one torrent with BitComet's padding, so I can’t completely correctly translate line #438:
"button-filter": "Type in regular expressions and click the paging button to refresh",

Question.
"paging button" or "padding button"?

### CODE REVIEW

**Comment by ronggang** [comment]
@imebeh 你来解译一下？

**Comment by imebeh** [comment]
files

I mean buttons in group 1. (translate with Google :) )

-------

| index | explanation |
| ----- | --------|
| 1 | These buttons will trigger data reload, filter is applied during loading. |
| 2 | I can't find a easy way to trigger the data reload right now, have to leave it to the buttons in group 1. (still learning JavaScript) |
| 3 | These options are templates. |

**Comment by vodek3** [comment]
I do not have field number 3...
See screenshot

**Comment by imebeh** [comment]
> I do not have field number 3...
> 
try `Ctrl + F5` 
if there is still no field 3, then the console should show some errors.

**Comment by vodek3** [comment]
> Ctrl + F5
The Same. Nothing has changed.

**Comment by imebeh** [comment]
> The Same. Nothing has changed.

Have you modified a few lines to load the beta code? In index.html
https://github.com/ronggang/transmission-web-control/blob/master/src/index.html#34


`<script type=“text/javascript” src=“tr-web-control/script/transmission.js?v=20190724”></script>
<script type=“text/javascript” src=“tr-web-control/script/transmission.torrents.js?v=20171027”></script>
<script type=“text/javascript” src=“tr-web-control/script/system.js?v=20190724”></script>`

**Comment by vodek3** [comment]
I modified Index.html (L34-L36)
Field 3 has appeared.

Y-Button

But with any choice ("All", "BitComet padding file", "Unnecessary files") the Y-button is inactive.

Y-Button_Inactive

I also created empty files with the names "____ padding_file _ # ..."
(____padding_file_0_if you see this file, please update to BitComet 0.85 or above____) and placed them in the download folder.
This does not affect Y-button activity.

**Comment by imebeh** [comment]
> This does not affect Y-button activity.

This button is disabled right now, click the refresh button in field 1 instead.



Filter works like Google search, but supports regular expressions. it’s useful when you want find specific files among a bunch of files.

for example, a .torrent file contains these files,
- video-01.avi
- video-01.nfo1
- video-02.avi
- video-02.nfo2
- ...
- video-99.mp4
- video-99.nfo99
I only want the video files, Transmission selected all files to download by default, so I need to get rid of those .nfo* files. 
My mouse will click to death in the old way, but now, I can do this in less than a minute: 

- enter this regular expression: `.*\.nfo\d*$` (in this case, `nfo` will also works)
- click the refresh button
- files table will only show .nfo* files
- check all, click ignore button
- job done

**Comment by vodek3** [comment]
Thanks for the explanation!
It's work.
Files_Sort

**Pull request closed without merging**
